const gallaryData=[
    {
        id:1,
        src:'./images/animal1.jpg',
        type:'animal',
    },
    {
        id:2,
        src:'./images/animal2.jpg',
        type:'animal',
    },
    {
        id:3,
        src:'./images/animal3.jpg',
        type:'animal',
    },
    {
        id:4,
        src:'./images/animal4.jpg',
        type:'animal',
    },
    {
        id:5,
        src:'./images/animal5.jpg',
        type:'animal',
    },
    {
        id:6,
        src:'./images/nature1.jpg',
        type:'nature',
    },
    {
        id:7,
        src:'./images/nature2.jpg',
        type:'nature',
    },
    {
        id:8,
        src:'./images/nature3.jpg',
        type:'nature',
    },
    {
        id:9,
        src:'./images/nature4.jpg',
        type:'nature',
    },
    {
        id:10,
        src:'./images/nature5.jpg',
        type:'nature',
    },
    {
        id:11,
        src:'./images/nature6.jpg',
        type:'nature',
    },
    {
        id:12,
        src:'./images/nature7.jpg',
        type:'nature',
    },
    {
        id:13,
        src:'./images/tech1.jpg',
        type:'tech',
    },
    {
        id:14,
        src:'./images/tech2.jpg',
        type:'tech',
    },
    {
        id:15,
        src:'./images/tech3.jpg',
        type:'tech',
    },
    {
        id:16,
        src:'./images/gaming1.jpg',
        type:'gaming',
    },
    {
        id:17,
        src:'./images/gaming2.jpg',
        type:'gaming',
    },
    {
        id:18,
        src:'./images/gaming4.jpg',
        type:'gaming',
    },
    {
        id:19,
        src:'./images/gaming5.jpg',
        type:'gaming',
    },
    {
        id:20,
        src:'./images/gaming6.jpg',
        type:'gaming',
    },
    {
        id:21,
        src:'./images/gaming7.jpg',
        type:'gaming',
    },
    {
        id:22,
        src:'./images/gaming8.jpg',
        type:'gaming',
    },
]